Use the dockerfile to creat the image

To Create the Image:
	docker build -t url_shortener:v1 .

To run the container with Image:
	docker run -d -p 5000:5000 url_shortener:v1

To Push to Docker Hub:
	Log in on https://hub.docker.com/
	
	Click on Create Repository.
	
	Choose a name (e.g. verse_gapminder) and a description for your repository and click Create.
	
	Log into the Docker Hub from the command line

	Step 1: First tag (rename) the Docker Image
		docker tag url_shortener_app:v2 bikigrg/url_shortener:v1

	Step 2: Docker Push 
		docker push bikigrg/url_shortener:v1


on the docker agent:
	install default-jre, python3-pip, python3.10-venv, docker

on the terraform agent:
	
